package hfycodec

import "strings"

const DefaultVersionCode = "099"

const fixedTextAuthorizationSuffix083 = "ENLILPIHHPJBGGOEFOEFCOONHAGDKKODIHHGNOMFAIHOLJNOEDKHHKPDIDDPHAFEPOHJDEGDICIALMGPAFEJNPEFOLDCIGJHKCHICNDLNGMMPEHGBADJLDFHGBCHFAFHCJHDHDKAILOEGCDHIALHHKPPGGKNJJDLGKGMCIAPAEPEPHPOFLBLKKDBGBGDKPGBHIAMCFHAKOJFNOGJPMMCAPPHHHKMFDHIFAFJMJOPIHCFOKBNNOJAMKBCDEKKIKOFFICLJJKPOLMNGMCKCFNBBMBAMIBPNFIAJOBIMHEDNPOBGGODIKOAOHHFGBAHLFCPDMBNOPELCKBHPIHHALFPBKPGIPBIBMEFKIAAMHMAJEHNLLGKHAINEJIDCDFNBACBACCLGNJCAGHFJIMKBKEEPJCMFCFGOIAMMHHMFNHLPBHMOALEIJFCPPFFIOJJODFLMEFPKCLLPMMNNAEPHLLEIHHDBOGFPHICKIEPLNJHILFJOGOPBCMIEKJFBDDMPPKFMDHJHHHKOLPKMBOCFIIEGFJCDJFKOHNBBCJGAEIDKALJLBKAIMKKLPLFAODADKMNIOJPBMHOBBOIAIGMLBLMELKEMOFOEKDFDOANIBIOPJGICFPNLHGDIDFNCMNBLGBNONGLPNEFINKPJGIBHLCBGAHGMCKCHMGGIBEIPKFCGHMMFEBGGGOJOADKHBNGAJJPFJBABDFLGMNJOJMFMEELGBGAEMHLAPMFKBKDLKDNHCNHGCEDPAIPCJEGEAGOMDOFMBCLKCAHINEGOCPMKPPMOJIJCOFJCMHDGMGKIHJLGOHNMDOCIIHHLBLCJLFCIHOJIPGGCKFPEAAGAIOKHGEJLAGKHMHDDOPGAEHOHCPCDCOEMEMGNEKCFJEKFNNAMCGOIJJAPHHNJHNBHNDOICEJABNPPFONKGILFJHNNDGMHEEFHPEJDDNCOCBNLMKFPEGNCNOGEMIKLLDBOJJHPGOJFPIMEDKDNAEBMHGGBHGNANJFBOJNPOHGEGHBGBMKIJFGLOJHIJDFGDIPBPMKAJMGMMLEOIHKGIMFICPFHMNALGCOPCNGIMHDLANBNHNIDCFLDAOBJMLNBO"

const fixedTextAuthorizationSuffix085 = "XFPMOFOBIPHMFPLAJLMHMOCBFEEHJCBEHFFCHIDOLCFIIAJMFDBENNOJFBDLDNJLCGAEEHCEHPKBJINKHLGACKDCAPADLKMNJDHIFKLOIFLADONPLKEGMFEFFPKAEJJDIBOLBGNJCELOFDPMLEBMKCBJCGELOLGDPKEFIOGEGPLIPMBCIJOFKOGHCDFKJGANEPCBNBMBLNHBPFIHKGECOELBLGBCGEAIEHDKDEDEMAKCNFAKJCBBGPJLEHMHHJLBAHICAOGOHFCENHIDHNABHNKODAABHHMLDDHHALOLGDIPLBHPKMIBPGEENNMBKAEGGNGANFFCEJLHIHEGDKEPMJBEIOEBDBFEEADMJKHHIDKBCLKGOGDNEKIPEGHIBJBCBEAJCKHDDKKBJLCNLKKEAADDEAKLPHJBLOIGOPOGENDMKPBDNAJKCCPCBLHNEBIPFJPMDMJOHFENDEBFDPAPKBHHMHEMJKHNKNKHKEEIEKINBMJGBJIHMBNMJIEAAMEAJHDHHDGOFGIIKBMPDHHGNPFCJABOFLJELAODJBLCELLNHEGPPHLNCMGOMNJHONNEFHEJMOABENKDHDJFJCGAFEPBENOHLEFCDBEDNIALABABIJHGFAFANJOEADFHOBPBHNGENOCDMJGPGNOBOKHABMPFLCFBMOKGMBNACOINFIGGNPGGHFDKAIKPGIHLLEOAFKHJMLLIPEDJKDENNBJMEFAAILNMNBMOIDKAJHGLABGCGFAAGAHBOAPAIOHNEKKNINJMLCGHICILDPBJOPANONCNNKDAJEFADPPOEIKLHEBPJIMIJFLDDLDKHEECJJPAIKDDHJLCIEGNMKEMMAKNLCHKAIKPGFBEEGBEDAMHCHOEJKKPJIKJHHKNFFDPLBNNOFAFFOCPBCFENBHAEDBFMPCFOBLNIDMDKFIKKJMDLJOPJDKIBKCDNNIEMNHHKNOHFIOBNJABGFLBPBCLMPICOEHNNJOKJBHDCAJEMAPAKENEAFBGCOFHGONHCCNMBMOLMPEFEBCFCALKDCKBONLJFGBFKHPKJBCGFPPDJMHEILKOJMCOHBDCJNDBGHFGPCFLIBJJJDCOHJ"

type VersionProfile struct {
	Code        string
	Label       string
	ProductName string
	Tail        string
}

var versionProfiles = []VersionProfile{
	{Code: "079", Label: "冒险岛", ProductName: "冒险岛", Tail: fixedTextAuthorizationSuffix},
	{Code: "083", Label: "083山茶冒险岛-装备扩展", ProductName: "083山茶冒险岛-装备扩展", Tail: fixedTextAuthorizationSuffix083},
	{Code: "085", Label: "神木村-角色潜能-自定义属性", ProductName: "神木村-角色潜能-自定义属性", Tail: fixedTextAuthorizationSuffix085},
	{Code: "095", Label: "095自定义属性-伤害统计-发面板包", ProductName: "095自定义属性-伤害统计-发面板包", Tail: fixedTextAuthorizationSuffix},
	{Code: "099", Label: "099冒险岛-自定义属性", ProductName: "099冒险岛-自定义属性", Tail: fixedTextAuthorizationSuffix},
}

var versionProfileMap = buildVersionProfileMap(versionProfiles)

func AvailableVersionProfiles() []VersionProfile {
	out := make([]VersionProfile, len(versionProfiles))
	copy(out, versionProfiles)
	return out
}

func NormalizeVersionCode(raw string) string {
	code := strings.TrimSpace(raw)
	if code == "" {
		return DefaultVersionCode
	}
	return code
}

func ResolveVersionProfile(raw string) (VersionProfile, bool) {
	code := NormalizeVersionCode(raw)
	profile, ok := versionProfileMap[code]
	return profile, ok
}

func buildVersionProfileMap(items []VersionProfile) map[string]VersionProfile {
	out := make(map[string]VersionProfile, len(items))
	for _, item := range items {
		out[item.Code] = item
	}
	return out
}
