#pragma once

#define IDR_BTN_NORMAL    101
#define IDR_BTN_HOVER     102
#define IDR_BTN_PRESSED   103
#define IDR_BTN_DISABLED  104
#define IDR_PANEL_BG      105
#define IDR_PANEL_TAB_PASSIVE_NORMAL      106
#define IDR_PANEL_TAB_PASSIVE_ACTIVE      107
#define IDR_PANEL_TAB_ACTIVE_NORMAL       108
#define IDR_PANEL_TAB_ACTIVE_ACTIVE       109
#define IDR_PANEL_INIT_NORMAL             110
#define IDR_PANEL_INIT_MOUSEOVER          111
#define IDR_PANEL_INIT_PRESSED            112
#define IDR_PANEL_INIT_DISABLED           113
#define IDR_PANEL_SCROLL_NORMAL           114
#define IDR_PANEL_SCROLL_PRESSED          115
#define IDR_PANEL_SPUP_NORMAL             116
#define IDR_PANEL_SPUP_DISABLED           117
#define IDR_PANEL_SPUP_PRESSED            118
#define IDR_PANEL_SPUP_MOUSEOVER          119
#define IDR_PANEL_SKILL_ROW_NORMAL        120
#define IDR_PANEL_SKILL_ROW_UPGRADE       121
#define IDR_PANEL_TYPEICON_ACTIVE         122
#define IDR_PANEL_TYPEICON_UNUSED         123
#define IDR_PANEL_TYPEICON_PASSIVE        124
#define IDR_CURSOR_NORMAL                 125
#define IDR_CURSOR_HOVER_A                126
#define IDR_CURSOR_HOVER_B                127
#define IDR_CURSOR_PRESSED                128
#define IDR_CURSOR_DRAG                   129
